import React, { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import { Label } from "@/components/ui/label";
import { 
  CheckCircle2, 
  AlertTriangle, 
  AlertCircle, 
  Download, 
  RefreshCw,
  Leaf,
  Activity,
  Percent,
  Info
} from "lucide-react";
import { cn } from "@/lib/utils";

export interface DiagnosisData {
  plant: string;
  disease: string;
  severity: "healthy" | "mild" | "severe";
  confidence: string;
  maskUrl?: string;
  recommendations?: string[];
}

interface DiagnosisResultProps {
  data: DiagnosisData;
  imagePreview: string;
  onScanNew: () => void;
}

const severityConfig = {
  healthy: {
    icon: CheckCircle2,
    label: "Healthy",
    colorClass: "bg-severity-healthy text-severity-healthy-foreground",
    borderClass: "border-severity-healthy/30",
    bgClass: "bg-severity-healthy/10",
    message: "Your plant looks healthy! Keep up the good care.",
  },
  mild: {
    icon: AlertTriangle,
    label: "Mild Disease",
    colorClass: "bg-severity-mild text-severity-mild-foreground",
    borderClass: "border-severity-mild/30",
    bgClass: "bg-severity-mild/10",
    message: "Early signs detected. Treatment recommended.",
  },
  severe: {
    icon: AlertCircle,
    label: "Severe Disease",
    colorClass: "bg-severity-severe text-severity-severe-foreground",
    borderClass: "border-severity-severe/30",
    bgClass: "bg-severity-severe/10",
    message: "Urgent action required. Immediate treatment needed.",
  },
};

export const DiagnosisResult: React.FC<DiagnosisResultProps> = ({
  data,
  imagePreview,
  onScanNew,
}) => {
  const [showMask, setShowMask] = useState(false);
  const config = severityConfig[data.severity];
  const Icon = config.icon;

  const handleDownload = () => {
    const report = `
AgriGuard AI - Plant Diagnosis Report
=====================================
Date: ${new Date().toLocaleDateString()}
Time: ${new Date().toLocaleTimeString()}

Plant: ${data.plant}
Disease: ${data.disease}
Severity: ${config.label}
Confidence: ${data.confidence}

${data.recommendations?.length ? `Recommendations:\n${data.recommendations.map((r, i) => `${i + 1}. ${r}`).join('\n')}` : ''}

---
Generated by AgriGuard AI
    `.trim();

    const blob = new Blob([report], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `agriguard-report-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="w-full max-w-lg mx-auto space-y-4 animate-slide-up">
      {/* Severity Banner */}
      <div className={cn(
        "flex items-center gap-3 p-4 rounded-xl border",
        config.borderClass,
        config.bgClass
      )}>
        <div className={cn("p-2 rounded-full", config.colorClass)}>
          <Icon className="h-5 w-5" />
        </div>
        <div className="flex-1">
          <p className="font-semibold text-foreground">{config.label}</p>
          <p className="text-sm text-muted-foreground">{config.message}</p>
        </div>
        <Badge className={config.colorClass}>{data.confidence}</Badge>
      </div>

      {/* Image Display with Mask Toggle */}
      <Card>
        <CardHeader className="pb-3">
          <div className="flex items-center justify-between">
            <CardTitle className="text-base font-medium">Visual Analysis</CardTitle>
            {data.maskUrl && (
              <div className="flex items-center gap-2">
                <Label htmlFor="mask-toggle" className="text-sm text-muted-foreground">
                  Show Disease Map
                </Label>
                <Switch
                  id="mask-toggle"
                  checked={showMask}
                  onCheckedChange={setShowMask}
                />
              </div>
            )}
          </div>
        </CardHeader>
        <CardContent>
          <div className="relative overflow-hidden rounded-lg">
            <img
              src={imagePreview}
              alt="Analyzed leaf"
              className={cn(
                "w-full h-auto transition-opacity duration-300",
                showMask && data.maskUrl ? "opacity-0" : "opacity-100"
              )}
            />
            {data.maskUrl && (
              <img
                src={data.maskUrl}
                alt="Disease mask overlay"
                className={cn(
                  "absolute inset-0 w-full h-full object-cover transition-opacity duration-300",
                  showMask ? "opacity-100" : "opacity-0"
                )}
              />
            )}
          </div>
        </CardContent>
      </Card>

      {/* Diagnosis Details */}
      <Card>
        <CardContent className="pt-6 space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <div className="flex items-start gap-3">
              <div className="p-2 rounded-lg bg-primary/10">
                <Leaf className="h-4 w-4 text-primary" />
              </div>
              <div>
                <p className="text-xs text-muted-foreground">Plant</p>
                <p className="font-medium text-foreground">{data.plant}</p>
              </div>
            </div>
            
            <div className="flex items-start gap-3">
              <div className="p-2 rounded-lg bg-primary/10">
                <Activity className="h-4 w-4 text-primary" />
              </div>
              <div>
                <p className="text-xs text-muted-foreground">Disease</p>
                <p className="font-medium text-foreground">{data.disease}</p>
              </div>
            </div>
            
            <div className="flex items-start gap-3">
              <div className="p-2 rounded-lg bg-primary/10">
                <Percent className="h-4 w-4 text-primary" />
              </div>
              <div>
                <p className="text-xs text-muted-foreground">Confidence</p>
                <p className="font-medium text-foreground">{data.confidence}</p>
              </div>
            </div>
          </div>

          {data.recommendations && data.recommendations.length > 0 && (
            <div className="pt-4 border-t border-border">
              <div className="flex items-center gap-2 mb-3">
                <Info className="h-4 w-4 text-primary" />
                <p className="font-medium text-foreground">Recommendations</p>
              </div>
              <ul className="space-y-2">
                {data.recommendations.map((rec, i) => (
                  <li key={i} className="text-sm text-muted-foreground flex items-start gap-2">
                    <span className="h-1.5 w-1.5 rounded-full bg-primary mt-2 shrink-0" />
                    {rec}
                  </li>
                ))}
              </ul>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Action Buttons */}
      <div className="flex gap-3">
        <Button onClick={handleDownload} variant="outline" className="flex-1">
          <Download className="h-4 w-4" />
          Download Report
        </Button>
        <Button onClick={onScanNew} className="flex-1">
          <RefreshCw className="h-4 w-4" />
          Scan New Leaf
        </Button>
      </div>
    </div>
  );
};
