import jsPDF from "jspdf";
import type { DiagnosisData } from "@/components/DiagnosisResult";

const severityLabels: Record<string, string> = {
  healthy: "Healthy",
  mild: "Mild Disease",
  severe: "Severe Disease",
};

const severityColors: Record<string, [number, number, number]> = {
  healthy: [34, 197, 94],
  mild: [234, 179, 8],
  severe: [239, 68, 68],
};

export function generateDiagnosisReport(data: DiagnosisData, imagePreview: string) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  // --- Header bar ---
  doc.setFillColor(15, 23, 42); // dark slate
  doc.rect(0, 0, pageWidth, 40, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("AgriGuard AI", margin, 18);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("Plant Disease Diagnosis Report", margin, 27);

  const dateStr = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  doc.setFontSize(9);
  doc.text(dateStr, pageWidth - margin, 27, { align: "right" });

  y = 50;

  // --- Severity banner ---
  const sevColor = severityColors[data.severity] || [100, 100, 100];
  doc.setFillColor(sevColor[0], sevColor[1], sevColor[2]);
  doc.roundedRect(margin, y, contentWidth, 18, 3, 3, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text(severityLabels[data.severity] || data.severity, margin + 8, y + 11);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`Confidence: ${data.confidence}`, pageWidth - margin - 8, y + 11, { align: "right" });

  y += 28;

  // --- Image ---
  try {
    const imgWidth = 70;
    const imgHeight = 52;
    doc.addImage(imagePreview, "JPEG", margin, y, imgWidth, imgHeight);

    // Details beside image
    const detailX = margin + imgWidth + 10;
    const detailW = contentWidth - imgWidth - 10;

    doc.setTextColor(30, 30, 30);
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");

    const details = [
      { label: "Plant Species", value: data.plant },
      { label: "Disease Detected", value: data.disease },
      { label: "Severity Level", value: severityLabels[data.severity] || data.severity },
      { label: "Confidence Score", value: data.confidence },
    ];

    let detailY = y + 4;
    details.forEach((d) => {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(120, 120, 120);
      doc.text(d.label, detailX, detailY);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      doc.setTextColor(30, 30, 30);
      doc.text(d.value, detailX, detailY + 5);
      detailY += 14;
    });

    y += imgHeight + 10;
  } catch {
    y += 5;
  }

  // --- Recommendations ---
  if (data.recommendations && data.recommendations.length > 0) {
    doc.setFillColor(241, 245, 249);
    doc.roundedRect(margin, y, contentWidth, 8, 2, 2, "F");
    doc.setTextColor(30, 30, 30);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Recommendations", margin + 5, y + 6);
    y += 14;

    data.recommendations.forEach((rec, i) => {
      doc.setFillColor(sevColor[0], sevColor[1], sevColor[2]);
      doc.circle(margin + 4, y + 1.5, 2.5, "F");
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(7);
      doc.setFont("helvetica", "bold");
      doc.text(String(i + 1), margin + 2.7, y + 3);

      doc.setTextColor(50, 50, 50);
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      const lines = doc.splitTextToSize(rec, contentWidth - 15);
      doc.text(lines, margin + 12, y + 3);
      y += lines.length * 5 + 4;
    });
  }

  // --- Footer ---
  const footerY = doc.internal.pageSize.getHeight() - 15;
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, footerY - 3, pageWidth - margin, footerY - 3);
  doc.setTextColor(150, 150, 150);
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.text("Generated by AgriGuard AI • agriguard.ai", margin, footerY);
  doc.text(`Report ID: AG-${Date.now().toString(36).toUpperCase()}`, pageWidth - margin, footerY, { align: "right" });

  doc.save(`AgriGuard-Report-${Date.now()}.pdf`);
}
